import * as assert from 'assert';
import { CodeGeneratorService } from '../generators/codeGeneratorService';
import { DdlGeneratorService } from '../generators/ddlGeneratorService';
import { DatabaseType, ProjectSchema } from '../types/schema';

function createSchema(database: DatabaseType): ProjectSchema {
  return {
    version: '1.0',
    entities: [
      {
        id: 'entity_user',
        name: 'User',
        attributes: [
          { id: 'user_id', name: 'id', type: 'Int', visibility: 'private', isPrimary: true, isNullable: false, isUnique: true },
          { id: 'user_preferences', name: 'preferences', type: 'JSON', visibility: 'private', isPrimary: false, isNullable: true, isUnique: false },
        ],
        position: { x: 0, y: 0 },
      },
      {
        id: 'entity_post',
        name: 'Post',
        attributes: [
          { id: 'post_id', name: 'id', type: 'Int', visibility: 'private', isPrimary: true, isNullable: false, isUnique: true },
          { id: 'post_published', name: 'publishedAt', type: 'DateTime', visibility: 'private', isPrimary: false, isNullable: false, isUnique: false },
          { id: 'post_price', name: 'price', type: 'Decimal', visibility: 'private', isPrimary: false, isNullable: false, isUnique: false },
          { id: 'post_attachment', name: 'attachment', type: 'Bytes', visibility: 'private', isPrimary: false, isNullable: true, isUnique: false },
        ],
        position: { x: 0, y: 300 },
      },
      {
        id: 'entity_tag',
        name: 'Tag',
        attributes: [
          { id: 'tag_id', name: 'id', type: 'Int', visibility: 'private', isPrimary: true, isNullable: false, isUnique: true },
          { id: 'tag_name', name: 'name', type: 'String', visibility: 'private', isPrimary: false, isNullable: false, isUnique: true },
        ],
        position: { x: 300, y: 300 },
      },
    ],
    relations: [
      {
        id: 'rel_user_posts',
        sourceClassId: 'entity_user',
        targetClassId: 'entity_post',
        type: 'OneToMany',
        umlType: 'association',
        sourceFieldName: 'posts',
        targetFieldName: 'author',
        relationOwner: 'target',
      },
      {
        id: 'rel_post_tags',
        sourceClassId: 'entity_post',
        targetClassId: 'entity_tag',
        type: 'ManyToMany',
        umlType: 'association',
        sourceFieldName: 'tags',
        targetFieldName: 'posts',
        relationOwner: 'source',
      },
    ],
    config: {
      targetLanguage: 'TypeScript',
      orm: 'Prisma',
      database,
      projectName: 'ddl',
    },
  };
}

suite('DDL Generator', () => {
  test('generates PostgreSQL-specific DDL', () => {
    const ddl = new DdlGeneratorService().generate(createSchema('PostgreSQL'));

    assert.ok(ddl.includes('JSONB'));
    assert.ok(ddl.includes('TIMESTAMP'));
    assert.ok(ddl.includes('NUMERIC(19,4)'));
    assert.ok(ddl.includes('BYTEA'));
    assert.ok(ddl.includes('CREATE TABLE post_tag'));
    assert.ok(ddl.includes('FOREIGN KEY (authorId) REFERENCES user(id)'));
  });

  test('generates MySQL-specific DDL', () => {
    const ddl = new DdlGeneratorService().generate(createSchema('MySQL'));

    assert.ok(ddl.includes('JSON'));
    assert.ok(ddl.includes('DATETIME(6)'));
    assert.ok(ddl.includes('DECIMAL(19,4)'));
    assert.ok(ddl.includes('LONGBLOB'));
    assert.ok(ddl.includes('AUTO_INCREMENT'));
  });

  test('CodeGeneratorService exposes ORM code and DDL artifacts together', async () => {
    const artifacts = await new CodeGeneratorService().generateArtifacts(createSchema('PostgreSQL'));

    assert.ok(artifacts.ormCode.includes('provider = "postgresql"'));
    assert.ok(artifacts.ddl.includes('CREATE TABLE user'));
  });

  test('throws when schema validation fails before DDL generation', () => {
    const invalidSchema = createSchema('PostgreSQL');
    invalidSchema.entities.push({
      id: 'entity_duplicate_user',
      name: 'User',
      attributes: [
        { id: 'dup_user_id', name: 'id', type: 'Int', visibility: 'private', isPrimary: true, isNullable: false, isUnique: true },
      ],
      position: { x: 20, y: 20 },
    });

    assert.throws(() => new DdlGeneratorService().generate(invalidSchema), /Duplicate entity name/);
  });

  test('respects custom table, column, and join table names', () => {
    const schema = createSchema('PostgreSQL');
    schema.entities[0].tableName = 'app_user';
    schema.entities[0].attributes[0].columnName = 'user_pk';
    schema.entities[2].tableName = 'label';
    schema.relations[1].joinTableName = 'post_label_map';

    const ddl = new DdlGeneratorService().generate(schema);

    assert.ok(ddl.includes('CREATE TABLE app_user'));
    assert.ok(ddl.includes('user_pk INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY'));
    assert.ok(ddl.includes('CREATE TABLE post_label_map'));
    assert.ok(ddl.includes('REFERENCES app_user(user_pk)'));
  });

  test('creates a unique foreign key column for one-to-one relations', () => {
    const schema: ProjectSchema = {
      version: '1.0',
      entities: [
        {
          id: 'entity_user',
          name: 'User',
          attributes: [
            { id: 'user_id', name: 'id', type: 'String', visibility: 'private', isPrimary: true, isNullable: false, isUnique: true },
          ],
          position: { x: 0, y: 0 },
        },
        {
          id: 'entity_profile',
          name: 'Profile',
          attributes: [
            { id: 'profile_id', name: 'id', type: 'String', visibility: 'private', isPrimary: true, isNullable: false, isUnique: true },
          ],
          position: { x: 0, y: 200 },
        },
      ],
      relations: [
        {
          id: 'rel_user_profile',
          sourceClassId: 'entity_user',
          targetClassId: 'entity_profile',
          type: 'OneToOne',
          umlType: 'association',
          sourceFieldName: 'profile',
          targetFieldName: 'user',
          relationOwner: 'source',
          onDelete: 'Cascade',
        },
      ],
      config: {
        targetLanguage: 'TypeScript',
        orm: 'Prisma',
        database: 'PostgreSQL',
        projectName: 'one_to_one',
      },
    };

    const ddl = new DdlGeneratorService().generate(schema);

    assert.ok(ddl.includes('profileId VARCHAR(255) NOT NULL'));
    assert.ok(ddl.includes('UNIQUE (profileId)'));
    assert.ok(ddl.includes('ON DELETE CASCADE'));
  });

  test('uses nullable foreign keys and ON DELETE SET NULL when configured', () => {
    const schema = createSchema('PostgreSQL');
    schema.relations[0].onDelete = 'SetNull';
    schema.relations[0].sourceMultiplicity = '1';
    schema.relations[0].targetMultiplicity = '0..*';

    const ddl = new DdlGeneratorService().generate(schema);

    assert.ok(ddl.includes('authorId INTEGER,'));
    assert.ok(ddl.includes('ON DELETE SET NULL'));
  });

  test('applies string length and decimal precision metadata to DDL columns', () => {
    const schema = createSchema('MySQL');
    schema.entities[0].attributes.push({
      id: 'user_display_name',
      name: 'displayName',
      type: 'String',
      visibility: 'private',
      isPrimary: false,
      isNullable: false,
      isUnique: false,
      length: 120,
    });
    schema.entities[1].attributes[2].precision = 10;
    schema.entities[1].attributes[2].scale = 2;

    const ddl = new DdlGeneratorService().generate(schema);

    assert.ok(ddl.includes('display_name VARCHAR(120) NOT NULL'));
    assert.ok(ddl.includes('price DECIMAL(10,2) NOT NULL'));
  });
});
