import { ProjectSchema } from '../../types/schema';
import { lowerFirst, getRepositoryEntities, getRepositoryPkName, getRepositoryPkType, getRepositoryRelationPlaceholders } from './common';
import { RepositoryGenerator } from '../repositoryGeneratorService';

export class PrismaRepositoryGenerator implements RepositoryGenerator {
  async generate(schema: ProjectSchema): Promise<string> {
    const entities = getRepositoryEntities(schema, 'Prisma');
    const output: string[] = [];

    output.push(`// Prisma repositories for ${schema.config.projectName || 'MyProject'}`);
    output.push(`// Generated by UML to ORM Code Generator`);
    output.push('');
    output.push(`import { Prisma, PrismaClient } from '@prisma/client';`);
    output.push('');

    for (const entity of entities) {
      const pkName = getRepositoryPkName(entity);
      const pkType = getRepositoryPkType(entity, 'ts');
      const delegateName = lowerFirst(entity.name);
      const relationPlaceholders = getRepositoryRelationPlaceholders(entity, schema);

      output.push(`export class ${entity.name}Repository {`);
      output.push(`  constructor(private readonly prisma: PrismaClient) {}`);
      output.push('');
      output.push(`  async create(data: Prisma.${entity.name}CreateInput) {`);
      output.push(`    return this.prisma.${delegateName}.create({ data });`);
      output.push(`  }`);
      output.push('');
      output.push(`  async findById(${pkName}: ${pkType}) {`);
      output.push(`    return this.prisma.${delegateName}.findUnique({ where: { ${pkName} } });`);
      output.push(`  }`);
      output.push('');
      output.push(`  async findAll() {`);
      output.push(`    return this.prisma.${delegateName}.findMany();`);
      output.push(`  }`);
      output.push('');
      output.push(`  async update(${pkName}: ${pkType}, data: Prisma.${entity.name}UpdateInput) {`);
      output.push(`    return this.prisma.${delegateName}.update({ where: { ${pkName} }, data });`);
      output.push(`  }`);
      output.push('');
      output.push(`  async delete(${pkName}: ${pkType}) {`);
      output.push(`    return this.prisma.${delegateName}.delete({ where: { ${pkName} } });`);
      output.push(`  }`);
      if (relationPlaceholders.length > 0) {
        output.push('');
        output.push(`  // Related entity access placeholder: ${relationPlaceholders.join(', ')}`);
      }
      output.push(`}`);
      output.push('');
    }

    return output.join('\n').trim();
  }
}
