import { ProjectSchema } from '../../types/schema';
import { getRepositoryModelImportStem, getRepositoryEntities, getRepositoryPkName, getRepositoryPkType, getRepositoryRelationPlaceholders } from './common';
import { RepositoryGenerator } from '../repositoryGeneratorService';

export class TypeOrmRepositoryGenerator implements RepositoryGenerator {
  async generate(schema: ProjectSchema): Promise<string> {
    const entities = getRepositoryEntities(schema, 'TypeORM');
    const importStem = getRepositoryModelImportStem(schema);
    const entityNames = entities.map((entity) => entity.name);
    const output: string[] = [];

    output.push(`// TypeORM repositories for ${schema.config.projectName || 'Project'}`);
    output.push(`// Generated by UML to ORM Code Generator`);
    output.push('');
    output.push(`import { DataSource, DeepPartial, Repository } from 'typeorm';`);
    if (entityNames.length > 0) {
      output.push(`import { ${entityNames.join(', ')} } from './${importStem}';`);
    }
    output.push('');

    for (const entity of entities) {
      const pkName = getRepositoryPkName(entity);
      const pkType = getRepositoryPkType(entity, 'ts');
      const relationPlaceholders = getRepositoryRelationPlaceholders(entity, schema);

      output.push(`export class ${entity.name}Repository {`);
      output.push(`  private readonly repository: Repository<${entity.name}>;`);
      output.push('');
      output.push(`  constructor(private readonly dataSource: DataSource) {`);
      output.push(`    this.repository = this.dataSource.getRepository(${entity.name});`);
      output.push(`  }`);
      output.push('');
      output.push(`  async create(data: DeepPartial<${entity.name}>): Promise<${entity.name}> {`);
      output.push(`    const entity = this.repository.create(data);`);
      output.push(`    return this.repository.save(entity);`);
      output.push(`  }`);
      output.push('');
      output.push(`  async findById(${pkName}: ${pkType}): Promise<${entity.name} | null> {`);
      output.push(`    return this.repository.findOne({ where: { ${pkName} } as any });`);
      output.push(`  }`);
      output.push('');
      output.push(`  async findAll(): Promise<${entity.name}[]> {`);
      output.push(`    return this.repository.find();`);
      output.push(`  }`);
      output.push('');
      output.push(`  async update(${pkName}: ${pkType}, data: DeepPartial<${entity.name}>): Promise<${entity.name} | null> {`);
      output.push(`    const entity = await this.findById(${pkName});`);
      output.push(`    if (!entity) {`);
      output.push(`      return null;`);
      output.push(`    }`);
      output.push(`    return this.repository.save(this.repository.merge(entity, data));`);
      output.push(`  }`);
      output.push('');
      output.push(`  async delete(${pkName}: ${pkType}): Promise<boolean> {`);
      output.push(`    const result = await this.repository.delete({ ${pkName} } as any);`);
      output.push(`    return Boolean(result.affected);`);
      output.push(`  }`);
      if (relationPlaceholders.length > 0) {
        output.push('');
        output.push(`  // Related entity access placeholder: ${relationPlaceholders.join(', ')}`);
      }
      output.push(`}`);
      output.push('');
    }

    return output.join('\n').trim();
  }
}
