import { DataType, DatabaseType } from '../types/schema';

export interface DdlDialectProfile {
  database: DatabaseType;
  scalarTypes: Record<DataType, string>;
  autoIncrementPrimaryKey: string;
  defaultStringPrimaryKeyType: string;
  buildForeignKeyConstraint(constraintName: string, columnName: string, targetTable: string, targetColumn: string, onDelete?: string): string;
}

const POSTGRES_PROFILE: DdlDialectProfile = {
  database: 'PostgreSQL',
  scalarTypes: {
    String: 'VARCHAR(255)',
    Int: 'INTEGER',
    Float: 'DOUBLE PRECISION',
    Boolean: 'BOOLEAN',
    DateTime: 'TIMESTAMP',
    JSON: 'JSONB',
    Bytes: 'BYTEA',
    Decimal: 'NUMERIC(19,4)',
  },
  autoIncrementPrimaryKey: 'INTEGER GENERATED BY DEFAULT AS IDENTITY',
  defaultStringPrimaryKeyType: 'VARCHAR(255)',
  buildForeignKeyConstraint: (constraintName, columnName, targetTable, targetColumn, onDelete) =>
    `CONSTRAINT ${constraintName} FOREIGN KEY (${columnName}) REFERENCES ${targetTable}(${targetColumn})${onDelete ? ` ON DELETE ${onDelete}` : ''}`,
};

const MYSQL_PROFILE: DdlDialectProfile = {
  database: 'MySQL',
  scalarTypes: {
    String: 'VARCHAR(255)',
    Int: 'INT',
    Float: 'DOUBLE',
    Boolean: 'BOOLEAN',
    DateTime: 'DATETIME(6)',
    JSON: 'JSON',
    Bytes: 'LONGBLOB',
    Decimal: 'DECIMAL(19,4)',
  },
  autoIncrementPrimaryKey: 'INT AUTO_INCREMENT',
  defaultStringPrimaryKeyType: 'VARCHAR(255)',
  buildForeignKeyConstraint: (constraintName, columnName, targetTable, targetColumn, onDelete) =>
    `CONSTRAINT ${constraintName} FOREIGN KEY (${columnName}) REFERENCES ${targetTable}(${targetColumn})${onDelete ? ` ON DELETE ${onDelete}` : ''}`,
};

export function getDdlDialectProfile(database: DatabaseType): DdlDialectProfile {
  return database === 'MySQL' ? MYSQL_PROFILE : POSTGRES_PROFILE;
}
