import { ProjectSchema, ClassEntity, Attribute, Method } from '../../types/schema';
import { CodeGenerator } from '../codeGeneratorService';
import { getDjangoDialectProfile } from '../ormDialectProfiles';
import { resolveDatabase } from '../../shared/ormCatalog';

export class DjangoGenerator implements CodeGenerator {
  async generate(schema: ProjectSchema): Promise<string> {
    if (schema.config.orm !== 'Django') {
      throw new Error('This generator only supports Django');
    }

    const database = resolveDatabase(schema.config);
    const dialect = getDjangoDialectProfile(database);
    let output = `# Django Models - Generated by UML to ORM Code Generator\n\n`;
    output += `# Target database: ${database}\n`;
    output += `# settings.py ENGINE: ${dialect.engine}\n\n`;
    output += `from django.db import models\nfrom django.utils import timezone\n\n`;

    // Generate enums first
    for (const entity of schema.entities) {
      if (entity.stereotype === 'enum') {
        output += this.generateEnum(entity);
        output += '\n\n';
      }
    }

    for (const entity of schema.entities) {
      if (entity.stereotype === 'enum') continue;
      output += this.generateModel(entity, schema);
      output += '\n\n';
    }

    return output.trim();
  }

  private generateEnum(entity: ClassEntity): string {
    let code = `class ${entity.name}(models.TextChoices):\n`;
    for (const attr of entity.attributes) {
      const upper = attr.name.toUpperCase();
      code += `    ${upper} = '${attr.name}', '${attr.name}'\n`;
    }
    return code;
  }

  private getParentClass(entityId: string, schema: ProjectSchema): ClassEntity | undefined {
    const inhRel = schema.relations.find(
      (r) => r.umlType === 'inheritance' && r.sourceClassId === entityId
    );
    return inhRel ? schema.entities.find((e) => e.id === inhRel.targetClassId) : undefined;
  }

  private generateModel(entity: ClassEntity, schema: ProjectSchema): string {
    let code = '';

    // Documentation
    if (entity.documentation) {
      code += `# ${entity.documentation}\n`;
    }

    // Inheritance: child extends parent model instead of models.Model
    const parentClass = this.getParentClass(entity.id, schema);
    const baseClass = parentClass ? parentClass.name : 'models.Model';
    code += `class ${entity.name}(${baseClass}):\n`;

    // Docstring
    if (entity.documentation) {
      code += `    """${entity.documentation}"""\n\n`;
    }

    // Attributes
    for (const attr of entity.attributes) {
      const isDefaultAutoPk = attr.isPrimary && attr.name === 'id' && attr.type === 'Int';
      if (!isDefaultAutoPk) {
        code += `    ${attr.name} = ${this.mapDjangoField(attr)}\n`;
      }
    }

    // Relation fields
    const rels = this.getEntityRelations(entity.id, schema);
    if (rels.length > 0) code += '\n';
    for (const rel of rels) {
      code += `    ${rel}\n`;
    }

    // Meta class
    code += `\n    class Meta:\n`;
    if (entity.stereotype === 'abstract') {
      code += `        abstract = True\n`;
    }
    code += `        db_table = '${this.camelToSnake(entity.name)}'\n`;
    code += `        verbose_name = '${entity.name}'\n`;
    code += `        verbose_name_plural = '${entity.name}s'\n`;

    // __str__
    code += `\n    def __str__(self):\n`;
    code += `        return str(self.pk)\n`;

    // Methods
    if (entity.methods && entity.methods.length > 0) {
      code += '\n';
      for (const method of entity.methods) {
        code += this.generateMethod(method);
      }
    }

    return code;
  }

  private getEntityRelations(entityId: string, schema: ProjectSchema): string[] {
    const lines: string[] = [];

    for (const rel of schema.relations) {
      // Skip structural UML relationships — no ORM mapping
      if (rel.umlType && ['inheritance', 'realization', 'dependency'].includes(rel.umlType)) continue;

      // Composition implies cascade delete
      const effectiveOnDelete = rel.umlType === 'composition' ? 'Cascade' : rel.onDelete;

      // Only the "many" side or FK side defines the field in Django
      if (rel.targetClassId === entityId && rel.type === 'OneToMany') {
        // This entity is the "many" side → ForeignKey
        const source = schema.entities.find((e) => e.id === rel.sourceClassId);
        if (!source) continue;
        const fieldName = rel.targetFieldName || this.camelToSnake(source.name);
        const onDel = effectiveOnDelete ? `models.${this.mapDjangoOnDelete(effectiveOnDelete)}` : 'models.CASCADE';
        const relatedName = rel.sourceFieldName || this.camelToSnake(schema.entities.find((e) => e.id === entityId)!.name) + 's';
        lines.push(`${fieldName} = models.ForeignKey('${source.name}', on_delete=${onDel}, related_name='${relatedName}')`);
      } else if (rel.sourceClassId === entityId && rel.type === 'OneToOne') {
        const target = schema.entities.find((e) => e.id === rel.targetClassId);
        if (!target) continue;
        const fieldName = rel.sourceFieldName || this.camelToSnake(target.name);
        const onDel = effectiveOnDelete ? `models.${this.mapDjangoOnDelete(effectiveOnDelete)}` : 'models.CASCADE';
        const relatedName = rel.targetFieldName || this.camelToSnake(schema.entities.find((e) => e.id === entityId)!.name);
        lines.push(`${fieldName} = models.OneToOneField('${target.name}', on_delete=${onDel}, related_name='${relatedName}')`);
      } else if (rel.sourceClassId === entityId && rel.type === 'ManyToMany') {
        const target = schema.entities.find((e) => e.id === rel.targetClassId);
        if (!target) continue;
        const fieldName = rel.sourceFieldName || this.camelToSnake(target.name) + 's';
        const relatedName = rel.targetFieldName || this.camelToSnake(schema.entities.find((e) => e.id === entityId)!.name) + 's';
        lines.push(`${fieldName} = models.ManyToManyField('${target.name}', related_name='${relatedName}', blank=True)`);
      }
    }

    return lines;
  }

  private generateMethod(method: Method): string {
    const params = ['self', ...method.parameters.map((p) => `${p.name}`)].join(', ');
    const decorator = method.isStatic ? '    @staticmethod\n' : '';
    const selfParam = method.isStatic
      ? method.parameters.map((p) => p.name).join(', ')
      : params;

    let code = decorator;
    code += `    def ${method.name}(${selfParam}):\n`;
    code += `        raise NotImplementedError\n\n`;
    return code;
  }

  private mapDjangoField(attr: Attribute): string {
    const kwargs: string[] = [];

    // Type-specific first arguments
    const typeArgs: { [key: string]: string } = {
      String: 'max_length=255',
      Decimal: 'max_digits=10, decimal_places=2',
    };
    const firstArg = typeArgs[attr.type];
    if (firstArg) kwargs.push(firstArg);

    if (attr.isNullable) {
      kwargs.push('null=True');
      kwargs.push('blank=True');
    }

    if (attr.isUnique) {
      kwargs.push('unique=True');
    }

    if (attr.isPrimary) {
      kwargs.push('primary_key=True');
    }

    if (attr.defaultValue) {
      kwargs.push(`default=${attr.defaultValue}`);
    }

    const kwargStr = kwargs.join(', ');

    const fieldType: { [key: string]: string } = {
      String: 'CharField',
      Int: 'IntegerField',
      Float: 'FloatField',
      Boolean: 'BooleanField',
      DateTime: 'DateTimeField',
      JSON: 'JSONField',
      Bytes: 'BinaryField',
      Decimal: 'DecimalField',
    };

    const djangoField = fieldType[attr.type] || 'CharField';
    return `models.${djangoField}(${kwargStr})`;
  }

  /** Map OnDeleteAction to Django's models.X constant */
  private mapDjangoOnDelete(action: string): string {
    const mapping: { [key: string]: string } = {
      'Cascade': 'CASCADE',
      'SetNull': 'SET_NULL',
      'SetDefault': 'SET_DEFAULT',
      'Restrict': 'RESTRICT',
    };
    return mapping[action] || 'CASCADE';
  }

  private camelToSnake(str: string): string {
    return str.replace(/[A-Z]/g, (letter, idx) => (idx === 0 ? letter.toLowerCase() : `_${letter.toLowerCase()}`));
  }
}
