import { ProjectSchema, Relation, ClassEntity, Attribute } from '../../types/schema';
import { CodeGenerator } from '../codeGeneratorService';

export class PrismaGenerator implements CodeGenerator {
  async generate(schema: ProjectSchema): Promise<string> {
    if (schema.config.orm !== 'Prisma') {
      throw new Error('This generator only supports Prisma');
    }

    let code = `// Prisma schema for ${schema.config.projectName || 'MyProject'}\n`;
    code += `// Generated by UML to ORM Code Generator\n\n`;
    code += `datasource db {\n  provider = "postgresql"\n  url      = env("DATABASE_URL")\n}\n\n`;
    code += `generator client {\n  provider = "prisma-client-js"\n}\n\n`;

    // Generate enums first
    for (const entity of schema.entities) {
      if (entity.stereotype === 'enum') {
        code += this.generateEnum(entity);
        code += '\n';
      }
    }

    for (const entity of schema.entities) {
      if (entity.stereotype === 'enum') continue; // already generated above
      code += this.generateModel(entity, schema);
      code += '\n';
    }

    return code;
  }

  private getParentClass(entityId: string, schema: ProjectSchema): ClassEntity | undefined {
    const inhRel = schema.relations.find(
      (r) => r.umlType === 'inheritance' && r.sourceClassId === entityId
    );
    return inhRel ? schema.entities.find((e) => e.id === inhRel.targetClassId) : undefined;
  }

  /** Find the PK type of a given entity (defaults to 'String') */
  private getPkType(entity: ClassEntity): string {
    const pk = entity.attributes.find((a) => a.isPrimary);
    return pk ? this.mapDataType(pk.type) : 'String';
  }

  private generateEnum(entity: ClassEntity): string {
    let code = `enum ${entity.name} {\n`;
    for (const attr of entity.attributes) {
      code += `  ${attr.name}\n`;
    }
    code += `}\n`;
    return code;
  }

  private generateAttrLine(attr: Attribute): string {
    const prismaType = this.mapDataType(attr.type);
    const parts: string[] = [`  ${attr.name}`];
    parts.push(attr.isNullable ? `${prismaType}?` : prismaType);
    if (attr.isPrimary) {
      parts.push('@id');
      // Auto-increment for Int PKs, cuid for String PKs
      if (!attr.defaultValue) {
        if (attr.type === 'Int') {
          parts.push('@default(autoincrement())');
        } else if (attr.type === 'String') {
          parts.push('@default(cuid())');
        }
      }
    }
    if (attr.isUnique && !attr.isPrimary) parts.push('@unique');
    if (attr.defaultValue) parts.push(`@default(${attr.defaultValue})`);
    return parts.join('  ');
  }

  private generateModel(entity: ClassEntity, schema: ProjectSchema): string {
    const parentClass = this.getParentClass(entity.id, schema);
    let code = '';
    if (parentClass) {
      code += `// Inherits from ${parentClass.name} (UML inheritance)\n`;
    }
    code += `model ${entity.name} {\n`;

    // If inheriting, copy parent attributes (Prisma has no native class inheritance)
    if (parentClass) {
      code += `  // ── Inherited fields from ${parentClass.name} ──\n`;
      for (const attr of parentClass.attributes) {
        code += this.generateAttrLine(attr) + '\n';
      }
      code += `  // ── Own fields ──\n`;
    }

    // Attributes
    for (const attr of entity.attributes) {
      code += this.generateAttrLine(attr) + '\n';
    }

    // Relations
    const rels = this.getRelationsForEntity(entity, schema);
    if (rels.length > 0) code += '\n';
    for (const rel of rels) {
      code += rel + '\n';
    }

    code += '}\n';
    return code;
  }

  private getRelationsForEntity(entity: ClassEntity, schema: ProjectSchema): string[] {
    const lines: string[] = [];

    for (const rel of schema.relations) {
      // Skip structural UML relationships — no ORM mapping
      if (rel.umlType && ['inheritance', 'realization', 'dependency'].includes(rel.umlType)) continue;

      // Composition implies cascade delete
      const effectiveOnDelete = rel.umlType === 'composition' ? 'Cascade' : rel.onDelete;
      const relationName = `${schema.entities.find((e) => e.id === rel.sourceClassId)?.name || ''}To${schema.entities.find((e) => e.id === rel.targetClassId)?.name || ''}`;

      if (rel.sourceClassId === entity.id) {
        // This entity is the source (owner side)
        const target = schema.entities.find((e) => e.id === rel.targetClassId);
        if (!target) continue;

        const fieldName = rel.sourceFieldName || this.lowerFirst(target.name) + (rel.type !== 'OneToOne' ? 's' : '');

        if (rel.type === 'OneToMany') {
          lines.push(`  ${fieldName}  ${target.name}[]  @relation("${relationName}")`);
        } else if (rel.type === 'OneToOne') {
          lines.push(`  ${fieldName}  ${target.name}?  @relation("${relationName}")`);
        } else if (rel.type === 'ManyToMany') {
          lines.push(`  ${fieldName}  ${target.name}[]  @relation("${relationName}")`);
        }
      } else if (rel.targetClassId === entity.id) {
        // This entity is the target (inverse side)
        const source = schema.entities.find((e) => e.id === rel.sourceClassId);
        if (!source) continue;

        const fieldName = rel.targetFieldName || this.lowerFirst(source.name);
        // Derive FK type from the source entity's PK type
        const fkType = this.getPkType(source);

        if (rel.type === 'OneToMany') {
          // Target side is ManyToOne: single reference + FK
          const fkName = `${fieldName}Id`;
          const onDel = effectiveOnDelete ? `, onDelete: ${effectiveOnDelete}` : '';
          lines.push(`  ${fieldName}    ${source.name}   @relation("${relationName}", fields: [${fkName}], references: [id]${onDel})`);
          lines.push(`  ${fkName}  ${fkType}`);
        } else if (rel.type === 'OneToOne') {
          const fkName = `${fieldName}Id`;
          const onDel = effectiveOnDelete ? `, onDelete: ${effectiveOnDelete}` : '';
          lines.push(`  ${fieldName}    ${source.name}   @relation("${relationName}", fields: [${fkName}], references: [id]${onDel})`);
          lines.push(`  ${fkName}  ${fkType}  @unique`);
        } else if (rel.type === 'ManyToMany') {
          lines.push(`  ${fieldName}  ${source.name}[]  @relation("${relationName}")`);
        }
      }
    }

    return lines;
  }

  private mapDataType(type: string): string {
    const mapping: { [key: string]: string } = {
      String: 'String',
      Int: 'Int',
      Float: 'Float',
      Boolean: 'Boolean',
      DateTime: 'DateTime',
      JSON: 'Json',
      Bytes: 'Bytes',
      Decimal: 'Decimal',
    };
    return mapping[type] || 'String';
  }

  private lowerFirst(str: string): string {
    return str.charAt(0).toLowerCase() + str.slice(1);
  }
}
