import { ProjectSchema, ClassEntity, Method } from '../../types/schema';
import { CodeGenerator } from '../codeGeneratorService';
import { getPrimaryAttributeName, getPrimaryAttributeType } from '../../domain/schema/schemaOperations';
import { getSQLAlchemyDialectProfile } from '../ormDialectProfiles';
import { resolveDatabase } from '../../shared/ormCatalog';

export class SQLAlchemyGenerator implements CodeGenerator {
  async generate(schema: ProjectSchema): Promise<string> {
    if (schema.config.orm !== 'SQLAlchemy') {
      throw new Error('This generator only supports SQLAlchemy');
    }

    const database = resolveDatabase(schema.config);
    const dialect = getSQLAlchemyDialectProfile(database);
    let output = `# SQLAlchemy Models - Generated by UML to ORM Code Generator\n\n`;
    output += `# Target database: ${database}\n`;
    output += `# Example engine: create_engine('${dialect.engineUrlPrefix}://user:password@localhost/${schema.config.projectName || 'database'}')\n\n`;
    output += `from sqlalchemy import ${dialect.sqlalchemyImports.join(', ')}\n`;
    for (const extraImport of dialect.extraImports) {
      output += `${extraImport}\n`;
    }
    output += `from sqlalchemy.ext.declarative import declarative_base\n`;
    output += `from sqlalchemy.orm import relationship, sessionmaker\n`;
    output += `from sqlalchemy import create_engine\n`;
    // Import Enum if needed
    const hasEnum = schema.entities.some((e) => e.stereotype === 'enum');
    if (hasEnum) {
      output += `import enum\n`;
      output += `from sqlalchemy import Enum as SAEnum\n`;
    }
    output += `\n`;

    output += `Base = declarative_base()\n\n`;

    // Generate Python enums first
    for (const entity of schema.entities) {
      if (entity.stereotype === 'enum') {
        output += this.generatePyEnum(entity);
        output += '\n\n';
      }
    }

    // Many-to-many association tables
    for (const rel of schema.relations) {
      if (rel.umlType && ['inheritance', 'realization', 'dependency'].includes(rel.umlType)) continue;
      if (rel.type === 'ManyToMany') {
        const src = schema.entities.find((e) => e.id === rel.sourceClassId);
        const tgt = schema.entities.find((e) => e.id === rel.targetClassId);
        if (!src || !tgt) continue;
        const tableName = `${this.camelToSnake(src.name)}_${this.camelToSnake(tgt.name)}`;
        const srcFkType = this.getFkColumnType(src, dialect);
        const tgtFkType = this.getFkColumnType(tgt, dialect);
        const srcPkName = this.camelToSnake(this.getPkName(src));
        const tgtPkName = this.camelToSnake(this.getPkName(tgt));
        output += `${tableName} = Table(\n`;
        output += `    '${tableName}',\n`;
        output += `    Base.metadata,\n`;
        output += `    Column('${this.camelToSnake(src.name)}_${srcPkName}', ${srcFkType}, ForeignKey('${this.camelToSnake(src.name)}.${srcPkName}'), primary_key=True),\n`;
        output += `    Column('${this.camelToSnake(tgt.name)}_${tgtPkName}', ${tgtFkType}, ForeignKey('${this.camelToSnake(tgt.name)}.${tgtPkName}'), primary_key=True),\n`;
        output += `)\n\n`;
      }
    }

    for (const entity of schema.entities) {
      if (entity.stereotype === 'enum') continue;
      output += this.generateModel(entity, schema, dialect);
      output += '\n\n';
    }

    return output.trim();
  }

  /** Get the SQLAlchemy column type for a FK referencing this entity's PK */
  private getFkColumnType(entity: ClassEntity, dialect: ReturnType<typeof getSQLAlchemyDialectProfile>): string {
    return this.mapDataType(getPrimaryAttributeType(entity), dialect);
  }

  private getPkName(entity: ClassEntity): string {
    return getPrimaryAttributeName(entity);
  }

  private generatePyEnum(entity: ClassEntity): string {
    let code = `class ${entity.name}(enum.Enum):\n`;
    for (const attr of entity.attributes) {
      code += `    ${attr.name.toUpperCase()} = '${attr.name}'\n`;
    }
    return code;
  }

  private getParentClass(entityId: string, schema: ProjectSchema): ClassEntity | undefined {
    const inhRel = schema.relations.find(
      (r) => r.umlType === 'inheritance' && r.sourceClassId === entityId
    );
    return inhRel ? schema.entities.find((e) => e.id === inhRel.targetClassId) : undefined;
  }

  private generateModel(entity: ClassEntity, schema: ProjectSchema, dialect: ReturnType<typeof getSQLAlchemyDialectProfile>): string {
    let code = '';

    // Documentation
    if (entity.documentation) {
      code += `# ${entity.documentation}\n`;
    }

    // Inheritance: child extends parent instead of Base
    const parentClass = this.getParentClass(entity.id, schema);
    const baseClass = parentClass ? parentClass.name : 'Base';
    code += `class ${entity.name}(${baseClass}):\n`;
    code += `    __tablename__ = '${this.camelToSnake(entity.name)}'\n`;
    if (entity.stereotype === 'abstract') {
      code += `    __abstract__ = True\n`;
    }
    code += `\n`;

    // Attributes
    for (const attr of entity.attributes) {
      const sqlType = this.mapDataType(attr.type, dialect);
      const parts: string[] = [sqlType];

      if (attr.isPrimary) parts.push('primary_key=True');
      if (!attr.isNullable && !attr.isPrimary) parts.push('nullable=False');
      if (attr.isUnique && !attr.isPrimary) parts.push('unique=True');
      if (attr.defaultValue) parts.push(`default=${attr.defaultValue}`);

      code += `    ${attr.name} = Column(${parts.join(', ')})\n`;
    }

    // Relation fields
    const rels = this.getEntityRelations(entity.id, schema, dialect);
    if (rels.length > 0) code += '\n';
    for (const rel of rels) {
      code += `    ${rel}\n`;
    }

    // Methods
    if (entity.methods && entity.methods.length > 0) {
      code += '\n';
      for (const method of entity.methods) {
        code += this.generateMethod(method);
      }
    }

    // __repr__
    const pkName = this.getPkName(entity);
    code += `\n    def __repr__(self):\n`;
    code += `        return f'<${entity.name}(${pkName}={self.${pkName}})>'\n`;

    return code;
  }

  private getEntityRelations(entityId: string, schema: ProjectSchema, dialect: ReturnType<typeof getSQLAlchemyDialectProfile>): string[] {
    const lines: string[] = [];

    for (const rel of schema.relations) {
      // Skip structural UML relationships — no ORM mapping
      if (rel.umlType && ['inheritance', 'realization', 'dependency'].includes(rel.umlType)) continue;

      // Composition implies cascade delete
      const effectiveOnDelete = rel.umlType === 'composition' ? 'Cascade' : rel.onDelete;

      if (rel.sourceClassId === entityId) {
        const target = schema.entities.find((e) => e.id === rel.targetClassId);
        if (!target) continue;
        const fieldName = rel.sourceFieldName || this.lowerFirst(target.name) + (rel.type !== 'OneToOne' ? 's' : '');

        if (rel.type === 'OneToMany') {
          lines.push(`${fieldName} = relationship('${target.name}', back_populates='${rel.targetFieldName || this.lowerFirst(schema.entities.find((e) => e.id === entityId)!.name)}')`);
        } else if (rel.type === 'OneToOne') {
          lines.push(`${fieldName} = relationship('${target.name}', back_populates='${rel.targetFieldName || this.lowerFirst(schema.entities.find((e) => e.id === entityId)!.name)}', uselist=False)`);
        } else if (rel.type === 'ManyToMany') {
          const src = schema.entities.find((e) => e.id === entityId)!;
          const tableName = `${this.camelToSnake(src.name)}_${this.camelToSnake(target.name)}`;
          lines.push(`${fieldName} = relationship('${target.name}', secondary=${tableName}, back_populates='${rel.targetFieldName || this.lowerFirst(src.name) + 's'}')`);
        }
      } else if (rel.targetClassId === entityId) {
        const source = schema.entities.find((e) => e.id === rel.sourceClassId);
        if (!source) continue;
        const fieldName = rel.targetFieldName || this.lowerFirst(source.name);

        if (rel.type === 'OneToMany') {
          // This is the ManyToOne side — add FK column + relationship
          const fkPkName = this.camelToSnake(this.getPkName(source));
          const fkCol = `${this.camelToSnake(source.name)}_${fkPkName}`;
          const fkType = this.getFkColumnType(source, dialect);
          const onDel = effectiveOnDelete ? `, ondelete='${effectiveOnDelete.toUpperCase()}'` : '';
          lines.push(`${fkCol} = Column(${fkType}, ForeignKey('${this.camelToSnake(source.name)}.${fkPkName}'${onDel}))`);
          lines.push(`${fieldName} = relationship('${source.name}', back_populates='${rel.sourceFieldName || this.lowerFirst(schema.entities.find((e) => e.id === entityId)!.name) + 's'}')`);
        } else if (rel.type === 'OneToOne') {
          const fkPkName = this.camelToSnake(this.getPkName(source));
          const fkCol = `${this.camelToSnake(source.name)}_${fkPkName}`;
          const fkType = this.getFkColumnType(source, dialect);
          lines.push(`${fkCol} = Column(${fkType}, ForeignKey('${this.camelToSnake(source.name)}.${fkPkName}'), unique=True)`);
          lines.push(`${fieldName} = relationship('${source.name}', back_populates='${rel.sourceFieldName || this.lowerFirst(schema.entities.find((e) => e.id === entityId)!.name)}')`);
        } else if (rel.type === 'ManyToMany') {
          const tableName = `${this.camelToSnake(source.name)}_${this.camelToSnake(schema.entities.find((e) => e.id === entityId)!.name)}`;
          const fn = rel.targetFieldName || this.lowerFirst(source.name) + 's';
          lines.push(`${fn} = relationship('${source.name}', secondary=${tableName}, back_populates='${rel.sourceFieldName || this.lowerFirst(schema.entities.find((e) => e.id === entityId)!.name) + 's'}')`);
        }
      }
    }

    return lines;
  }

  private generateMethod(method: Method): string {
    const params = ['self', ...method.parameters.map((p) => `${p.name}: ${this.mapPyType(p.type)}`)].join(', ');
    const retType = method.returnType === 'void' ? 'None' : this.mapPyType(method.returnType);
    const decorator = method.isStatic ? '    @staticmethod\n' : '';
    const selfParam = method.isStatic
      ? method.parameters.map((p) => `${p.name}: ${this.mapPyType(p.type)}`).join(', ')
      : params;

    let code = decorator;
    code += `    def ${method.name}(${selfParam}) -> ${retType}:\n`;
    code += `        raise NotImplementedError\n\n`;
    return code;
  }

  private mapDataType(type: string, dialect: ReturnType<typeof getSQLAlchemyDialectProfile>): string {
    return dialect.dataTypeByType[type as keyof typeof dialect.dataTypeByType] || 'String(255)';
  }

  private mapPyType(type: string): string {
    const map: { [key: string]: string } = { String: 'str', Int: 'int', Float: 'float', Boolean: 'bool', DateTime: 'datetime', void: 'None' };
    return map[type] || type;
  }

  private camelToSnake(str: string): string {
    return str.replace(/[A-Z]/g, (letter, idx) => (idx === 0 ? letter.toLowerCase() : `_${letter.toLowerCase()}`));
  }

  private lowerFirst(str: string): string {
    return str.charAt(0).toLowerCase() + str.slice(1);
  }
}
