import { ProjectSchema, ClassEntity, Attribute, Method } from '../../types/schema';
import { CodeGenerator } from '../codeGeneratorService';
import { getPrimaryAttributeName } from '../../domain/schema/schemaOperations';
import { getTypeOrmDialectProfile } from '../ormDialectProfiles';
import { resolveDatabase } from '../../shared/ormCatalog';

export class TypeORMGenerator implements CodeGenerator {
  async generate(schema: ProjectSchema): Promise<string> {
    if (schema.config.orm !== 'TypeORM') {
      throw new Error('This generator only supports TypeORM');
    }

    const database = resolveDatabase(schema.config);
    const dialect = getTypeOrmDialectProfile(database);
    let output = `// TypeORM Entities - Generated by UML to ORM Code Generator\n\n`;
    output += `// Target database: ${database}\n`;
    output += `// Example DataSource type: ${dialect.dataSourceType}\n\n`;

    // Generate enums first
    for (const entity of schema.entities) {
      if (entity.stereotype === 'enum') {
        output += this.generateEnum(entity);
        output += '\n\n';
      }
    }

    for (const entity of schema.entities) {
      if (entity.stereotype === 'enum') continue;
      output += this.generateEntityClass(entity, schema, dialect);
      output += '\n\n';
    }

    return output.trim();
  }

  private generateEnum(entity: ClassEntity): string {
    let code = `export enum ${entity.name} {\n`;
    for (const attr of entity.attributes) {
      code += `  ${attr.name.toUpperCase()} = '${attr.name}',\n`;
    }
    code += `}\n`;
    return code;
  }

  // ─── Inheritance / Realization helpers ──────────────────────────────

  private getParentClass(entityId: string, schema: ProjectSchema): ClassEntity | undefined {
    const inhRel = schema.relations.find(
      (r) => r.umlType === 'inheritance' && r.sourceClassId === entityId
    );
    return inhRel ? schema.entities.find((e) => e.id === inhRel.targetClassId) : undefined;
  }

  private getInterfaces(entityId: string, schema: ProjectSchema): ClassEntity[] {
    return schema.relations
      .filter((r) => r.umlType === 'realization' && r.sourceClassId === entityId)
      .map((r) => schema.entities.find((e) => e.id === r.targetClassId))
      .filter((e): e is ClassEntity => !!e);
  }

  private generateEntityClass(entity: ClassEntity, schema: ProjectSchema, dialect: ReturnType<typeof getTypeOrmDialectProfile>): string {
    const imports = new Set<string>();
    const isInterface = entity.stereotype === 'interface';

    // Only add ORM imports for non-interface entities
    if (!isInterface) {
      imports.add('Entity');
      imports.add('Column');
    }

    const hasPK = entity.attributes.some((a) => a.isPrimary);
    if (hasPK && !isInterface) imports.add('PrimaryGeneratedColumn');

    // Check relations for this entity
    const rels = this.getEntityRelations(entity.id, schema);
    for (const rel of rels) {
      if (rel.decorator === 'OneToMany') imports.add('OneToMany');
      if (rel.decorator === 'ManyToOne') imports.add('ManyToOne');
      if (rel.decorator === 'OneToOne') imports.add('OneToOne');
      if (rel.decorator === 'ManyToMany') imports.add('ManyToMany');
      if (rel.needsJoinColumn) imports.add('JoinColumn');
      if (rel.needsJoinTable) imports.add('JoinTable');
    }

    // Inheritance / Realization
    const parentClass = this.getParentClass(entity.id, schema);
    const interfaces = this.getInterfaces(entity.id, schema);

    let code = '';
    if (imports.size > 0) {
      code += `import { ${Array.from(imports).join(', ')} } from 'typeorm';\n`;
    }
    if (parentClass) {
      code += `import { ${parentClass.name} } from './${parentClass.name}';\n`;
    }
    for (const iface of interfaces) {
      code += `import { ${iface.name} } from './${iface.name}';\n`;
    }
    code += `\n`;

    // Documentation
    if (entity.documentation) {
      code += `/**\n * ${entity.documentation}\n */\n`;
    }

    // Interface stereotype → no @Entity
    if (!isInterface) {
      code += `@Entity()\n`;
    }

    // Build class declaration
    const isAbstract = entity.stereotype === 'abstract';
    const classKeyword = isInterface
      ? 'export interface'
      : isAbstract ? 'export abstract class' : 'export class';
    const extendsClause = parentClass ? ` extends ${parentClass.name}` : '';
    const implClause = interfaces.length > 0 && !isInterface
      ? ` implements ${interfaces.map((i) => i.name).join(', ')}`
      : '';
    code += `${classKeyword} ${entity.name}${extendsClause}${implClause} {\n`;

    // Primary key fields
    for (const attr of entity.attributes) {
      if (attr.isPrimary) {
        code += this.generatePKField(attr);
      }
    }

    // Regular fields
    for (const attr of entity.attributes) {
      if (!attr.isPrimary) {
        code += this.generateField(attr, dialect);
      }
    }

    // Relation fields
    for (const rel of rels) {
      code += this.generateRelationField(rel);
    }

    // Methods
    if (entity.methods && entity.methods.length > 0) {
      code += '\n';
      for (const method of entity.methods) {
        code += this.generateMethod(method);
      }
    }

    code += `}\n`;
    return code;
  }

  private generatePKField(attr: Attribute): string {
    let code = '';
    if (attr.type === 'Int') {
      code += `  @PrimaryGeneratedColumn()\n`;
      code += `  ${attr.name}!: number;\n\n`;
    } else {
      code += `  @PrimaryGeneratedColumn('uuid')\n`;
      code += `  ${attr.name}!: string;\n\n`;
    }
    return code;
  }

  private generateField(attr: Attribute, dialect: ReturnType<typeof getTypeOrmDialectProfile>): string {
    let code = '';
    const opts = this.getColumnOptions(attr, dialect);
    if (attr.isNullable) opts.push('nullable: true');
    if (attr.isUnique) opts.push('unique: true');
    if (attr.defaultValue) opts.push(`default: ${attr.defaultValue}`);

    const optStr = opts.length > 0 ? `{ ${opts.join(', ')} }` : '';
    code += `  @Column(${optStr})\n`;

    const tsType = this.mapDataType(attr.type);
    const nullMark = attr.isNullable ? '?' : '!';
    const vis = attr.visibility === 'public' ? '' : attr.visibility === 'protected' ? 'protected ' : 'private ';
    const stat = attr.isStatic ? 'static ' : '';
    code += `  ${vis}${stat}${attr.name}${nullMark}: ${tsType};\n\n`;
    return code;
  }

  private getColumnOptions(attr: Attribute, dialect: ReturnType<typeof getTypeOrmDialectProfile>): string[] {
    return [...(dialect.columnOptionsByType[attr.type] || [])];
  }

  private generateRelationField(rel: {
    decorator: string;
    targetName: string;
    fieldName: string;
    isArray: boolean;
    needsJoinColumn: boolean;
    needsJoinTable: boolean;
    joinColumnName?: string;
    referencedColumnName?: string;
    inverseSide?: string;
    mappedBy?: string;
    onDelete?: string;
  }): string {
    let code = '';
    const onDelOpt = rel.onDelete ? `, { onDelete: '${rel.onDelete}' }` : '';

    if (rel.decorator === 'OneToMany') {
      code += `  @OneToMany(() => ${rel.targetName}, (${this.lowerFirst(rel.targetName)}) => ${this.lowerFirst(rel.targetName)}.${rel.inverseSide || this.lowerFirst(rel.targetName)})\n`;
      code += `  ${rel.fieldName}!: ${rel.targetName}[];\n\n`;
    } else if (rel.decorator === 'ManyToOne') {
      code += `  @ManyToOne(() => ${rel.targetName}${onDelOpt})\n`;
      if (rel.needsJoinColumn) {
        const joinOpts = rel.joinColumnName
          ? `{ name: '${rel.joinColumnName}'${rel.referencedColumnName ? `, referencedColumnName: '${rel.referencedColumnName}'` : ''} }`
          : '';
        code += `  @JoinColumn(${joinOpts})\n`;
      }
      code += `  ${rel.fieldName}!: ${rel.targetName};\n\n`;
    } else if (rel.decorator === 'OneToOne') {
      if (rel.needsJoinColumn) {
        code += `  @OneToOne(() => ${rel.targetName}${onDelOpt})\n`;
        const joinOpts = rel.joinColumnName
          ? `{ name: '${rel.joinColumnName}'${rel.referencedColumnName ? `, referencedColumnName: '${rel.referencedColumnName}'` : ''} }`
          : '';
        code += `  @JoinColumn(${joinOpts})\n`;
      } else {
        code += `  @OneToOne(() => ${rel.targetName}, (${this.lowerFirst(rel.targetName)}) => ${this.lowerFirst(rel.targetName)}.${rel.inverseSide || this.lowerFirst(rel.targetName)})\n`;
      }
      code += `  ${rel.fieldName}!: ${rel.targetName};\n\n`;
    } else if (rel.decorator === 'ManyToMany') {
      if (rel.needsJoinTable) {
        code += `  @ManyToMany(() => ${rel.targetName})\n`;
        code += `  @JoinTable()\n`;
      } else {
        code += `  @ManyToMany(() => ${rel.targetName}, (${this.lowerFirst(rel.targetName)}) => ${this.lowerFirst(rel.targetName)}.${rel.inverseSide || this.lowerFirst(rel.targetName)})\n`;
      }
      code += `  ${rel.fieldName}!: ${rel.targetName}[];\n\n`;
    }

    return code;
  }

  private generateMethod(method: Method): string {
    const vis = method.visibility === 'public' ? '' : method.visibility === 'protected' ? 'protected ' : 'private ';
    const stat = method.isStatic ? 'static ' : '';
    const params = method.parameters.map((p) => `${p.name}: ${p.type}`).join(', ');
    const returnType = method.returnType || 'void';

    return `  // UML method placeholder: ${vis}${stat}${method.name}(${params}): ${returnType}\n\n`;
  }

  private getEntityRelations(entityId: string, schema: ProjectSchema): Array<{
    decorator: string;
    targetName: string;
    fieldName: string;
    isArray: boolean;
    needsJoinColumn: boolean;
    needsJoinTable: boolean;
    joinColumnName?: string;
    referencedColumnName?: string;
    inverseSide?: string;
    mappedBy?: string;
    onDelete?: string;
  }> {
    const results: Array<any> = [];

    for (const rel of schema.relations) {
      // Skip structural UML relationships — no ORM mapping
      if (rel.umlType && ['inheritance', 'realization', 'dependency'].includes(rel.umlType)) continue;

      // Composition implies cascade delete
      const effectiveOnDelete = rel.umlType === 'composition' ? 'Cascade' : rel.onDelete;

      if (rel.sourceClassId === entityId) {
        const target = schema.entities.find((e) => e.id === rel.targetClassId);
        if (!target) continue;

        if (rel.type === 'OneToMany') {
          const sourcePkName = getPrimaryAttributeName(schema.entities.find((e) => e.id === entityId)!);
          results.push({
            decorator: 'OneToMany',
            targetName: target.name,
            fieldName: rel.sourceFieldName || this.lowerFirst(target.name) + 's',
            isArray: true,
            needsJoinColumn: false,
            needsJoinTable: false,
            inverseSide: rel.targetFieldName || this.lowerFirst(schema.entities.find((e) => e.id === entityId)!.name),
            referencedColumnName: sourcePkName,
          });
        } else if (rel.type === 'OneToOne') {
          const targetPkName = getPrimaryAttributeName(target);
          const joinColumnName = targetPkName === 'id'
            ? `${rel.sourceFieldName || this.lowerFirst(target.name)}Id`
            : `${rel.sourceFieldName || this.lowerFirst(target.name)}${this.upperFirst(targetPkName)}`;
          results.push({
            decorator: 'OneToOne',
            targetName: target.name,
            fieldName: rel.sourceFieldName || this.lowerFirst(target.name),
            isArray: false,
            needsJoinColumn: true,
            needsJoinTable: false,
            joinColumnName,
            referencedColumnName: targetPkName,
            onDelete: effectiveOnDelete,
          });
        } else if (rel.type === 'ManyToMany') {
          results.push({
            decorator: 'ManyToMany',
            targetName: target.name,
            fieldName: rel.sourceFieldName || this.lowerFirst(target.name) + 's',
            isArray: true,
            needsJoinColumn: false,
            needsJoinTable: true,
          });
        }
      } else if (rel.targetClassId === entityId) {
        const source = schema.entities.find((e) => e.id === rel.sourceClassId);
        if (!source) continue;

        if (rel.type === 'OneToMany') {
          const sourcePkName = getPrimaryAttributeName(source);
          const joinColumnName = sourcePkName === 'id'
            ? `${rel.targetFieldName || this.lowerFirst(source.name)}Id`
            : `${rel.targetFieldName || this.lowerFirst(source.name)}${this.upperFirst(sourcePkName)}`;
          results.push({
            decorator: 'ManyToOne',
            targetName: source.name,
            fieldName: rel.targetFieldName || this.lowerFirst(source.name),
            isArray: false,
            needsJoinColumn: true,
            needsJoinTable: false,
            joinColumnName,
            referencedColumnName: sourcePkName,
            onDelete: effectiveOnDelete,
          });
        } else if (rel.type === 'OneToOne') {
          results.push({
            decorator: 'OneToOne',
            targetName: source.name,
            fieldName: rel.targetFieldName || this.lowerFirst(source.name),
            isArray: false,
            needsJoinColumn: false,
            needsJoinTable: false,
            inverseSide: rel.sourceFieldName || this.lowerFirst(source.name),
          });
        } else if (rel.type === 'ManyToMany') {
          results.push({
            decorator: 'ManyToMany',
            targetName: source.name,
            fieldName: rel.targetFieldName || this.lowerFirst(source.name) + 's',
            isArray: true,
            needsJoinColumn: false,
            needsJoinTable: false,
            inverseSide: rel.sourceFieldName || this.lowerFirst(schema.entities.find((e) => e.id === entityId)!.name) + 's',
          });
        }
      }
    }

    return results;
  }

  private mapDataType(type: string): string {
    const mapping: { [key: string]: string } = {
      String: 'string',
      Int: 'number',
      Float: 'number',
      Boolean: 'boolean',
      DateTime: 'Date',
      JSON: 'object',
      Bytes: 'Buffer',
      Decimal: 'number',
    };
    return mapping[type] || 'string';
  }

  private lowerFirst(str: string): string {
    return str.charAt(0).toLowerCase() + str.slice(1);
  }

  private upperFirst(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }
}
