# SQLAlchemy Models - Generated by UML to ORM Code Generator

from sqlalchemy import Column, Integer, String, Boolean, DateTime, Float, Numeric, LargeBinary, Text, ForeignKey, Table
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, sessionmaker
from sqlalchemy import create_engine

Base = declarative_base()

post_tag = Table(
    'post_tag',
    Base.metadata,
    Column('post_id', String(255), ForeignKey('post.id'), primary_key=True),
    Column('tag_id', String(255), ForeignKey('tag.id'), primary_key=True),
)

role_permission = Table(
    'role_permission',
    Base.metadata,
    Column('role_id', String(255), ForeignKey('role.id'), primary_key=True),
    Column('permission_id', String(255), ForeignKey('permission.id'), primary_key=True),
)

user_role = Table(
    'user_role',
    Base.metadata,
    Column('user_id', String(255), ForeignKey('user.id'), primary_key=True),
    Column('role_id', String(255), ForeignKey('role.id'), primary_key=True),
)

class BaseEntity(Base):
    __tablename__ = 'base_entity'
    __abstract__ = True

    id = Column(String(255), primary_key=True)
    createdAt = Column(DateTime, nullable=False, default=now())

    def __repr__(self):
        return f'<BaseEntity(id={self.id})>'


class User(BaseEntity):
    __tablename__ = 'user'

    id = Column(String(255), primary_key=True)
    email = Column(String(255), nullable=False, unique=True)
    name = Column(String(255), nullable=False)

    profile = relationship('Profile', back_populates='user', uselist=False)
    posts = relationship('Post', back_populates='user')
    roles = relationship('Role', secondary=user_role, back_populates='users')

    def __repr__(self):
        return f'<User(id={self.id})>'


class Profile(Base):
    __tablename__ = 'profile'

    id = Column(String(255), primary_key=True)
    bio = Column(String(255))

    user_id = Column(String(255), ForeignKey('user.id'), unique=True)
    user = relationship('User', back_populates='profile')

    def __repr__(self):
        return f'<Profile(id={self.id})>'


class Role(Base):
    __tablename__ = 'role'

    id = Column(String(255), primary_key=True)
    name = Column(String(255), nullable=False, unique=True)

    permissions = relationship('Permission', secondary=role_permission, back_populates='roles')
    users = relationship('User', secondary=user_role, back_populates='roles')

    def __repr__(self):
        return f'<Role(id={self.id})>'


class Permission(Base):
    __tablename__ = 'permission'

    id = Column(String(255), primary_key=True)
    code = Column(String(255), nullable=False, unique=True)

    roles = relationship('Role', secondary=role_permission, back_populates='permissions')

    def __repr__(self):
        return f'<Permission(id={self.id})>'


class Post(Base):
    __tablename__ = 'post'

    id = Column(String(255), primary_key=True)
    title = Column(String(255), nullable=False)
    published = Column(Boolean, nullable=False, default=false)

    user_id = Column(String(255), ForeignKey('user.id', ondelete='RESTRICT'))
    user = relationship('User', back_populates='posts')
    comments = relationship('Comment', back_populates='post')
    category_id = Column(String(255), ForeignKey('category.id', ondelete='SETNULL'))
    category = relationship('Category', back_populates='posts')
    tags = relationship('Tag', secondary=post_tag, back_populates='posts')

    def __repr__(self):
        return f'<Post(id={self.id})>'


class Comment(Base):
    __tablename__ = 'comment'

    id = Column(String(255), primary_key=True)
    content = Column(String(255), nullable=False)

    post_id = Column(String(255), ForeignKey('post.id', ondelete='CASCADE'))
    post = relationship('Post', back_populates='comments')

    def __repr__(self):
        return f'<Comment(id={self.id})>'


class Category(Base):
    __tablename__ = 'category'

    id = Column(String(255), primary_key=True)
    name = Column(String(255), nullable=False, unique=True)

    posts = relationship('Post', back_populates='category')

    def __repr__(self):
        return f'<Category(id={self.id})>'


class Tag(Base):
    __tablename__ = 'tag'

    id = Column(String(255), primary_key=True)
    name = Column(String(255), nullable=False, unique=True)

    posts = relationship('Post', secondary=post_tag, back_populates='tags')

    def __repr__(self):
        return f'<Tag(id={self.id})>'


class NotificationService(Base):
    __tablename__ = 'notification_service'

    id = Column(String(255), primary_key=True)

    def notify(self, message: str) -> None:
        raise NotImplementedError


    def __repr__(self):
        return f'<NotificationService(id={self.id})>'